[customizations.installer.kickstart]
contents = """
%post --erroronfail --log=/root/anaconda-post.log
bootc switch --mutate-in-place --transport registry --enforce-container-sigpolicy <UPDATE_IMAGE_REF>

%end
"""
