---
name: Build image
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

env:
  IMAGE_NAME: "${{ github.event.repository.name }}"
  LATEST_TAG: "latest"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-image:
    uses: alexiri/build_image/.github/workflows/reusable-workflow.yml@main
    with:
      containerfile: Containerfile
      image-name: "${{ github.event.repository.name }}"
      latest-tag: "latest" # ${{ env.LATEST_TAG }}
      platforms: "amd64"
    secrets:
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    permissions:
      contents: read
      packages: write
      id-token: write

  test-image:
    name: Test image
    runs-on: ubuntu-latest
    needs: build-image

    env:
      IMAGE_REF: "${{ needs.build-image.outputs.image-ref }}@${{ needs.build-image.outputs.digest }}"

    steps:
      - name: Test container
        run: |
          # Create a short script to test the image using heredoc
          cat << 'EOF' > /tmp/test.sh
          set -ex

          cat /etc/os-release
          bootc -V
          EOF

          podman run --rm \
            -v /tmp/test.sh:/tmp/test.sh \
            ${{ env.IMAGE_REF }} \
            /bin/bash /tmp/test.sh

  promote-image:
    name: Promote image
    runs-on: ubuntu-latest
    needs: [build-image, test-image]

    env:
      IMAGE_REF: ${{ needs.build-image.outputs.image-ref }}
      DIGEST: ${{ needs.build-image.outputs.digest }}

    steps:
      - name: Log in to ghcr.io
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Promote image
        run: |
          podman pull ${{ env.IMAGE_REF }}@${{ env.DIGEST }}
          podman tag ${{ env.IMAGE_REF }}@${{ env.DIGEST }} ${{ env.IMAGE_REF }}:${{ env.LATEST_TAG }}
          podman push ${{ env.IMAGE_REF }}:${{ env.LATEST_TAG }}
