---
name: Build image
on:
  pull_request:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

env:
  IMAGE_NAME: "${{ github.event.repository.name }}"
  LATEST_TAG: "latest"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  debug-iso:
    name: debug - Build ISO
    uses: alexiri/build_image/.github/workflows/build-iso.yml@main
    with:
      image-name: "${{ github.event.repository.name }}"
      image: "ghcr.io/alexiri/blueshift_v4@ sha256:2decf49d439cc4cea9fcaa5ae7902dbbcea0a20b35cd6d89a675f949efef66c8 "
      update_origin_ref: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest"
      config-file: iso.toml
      platforms: "amd64" #"amd64,arm64"

  build-image:
    name: Build image
    uses: alexiri/build_image/.github/workflows/build-image.yml@main
    with:
      containerfile: Containerfile
      image-name: "${{ github.event.repository.name }}"
      previous-image: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest"
      platforms: "amd64,arm64"
    secrets:
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    permissions:
      contents: read
      packages: write
      id-token: write

  test-image:
    name: Test image
    runs-on: ubuntu-latest
    needs: build-image

    env:
      IMAGE_REF: "${{ needs.build-image.outputs.image-ref }}@${{ needs.build-image.outputs.digest }}"

    steps:
      - name: Test container
        run: |
          # Create a short script to test the image using heredoc
          cat << 'EOF' > /tmp/test.sh
          set -ex

          cat /etc/os-release
          bootc -V
          EOF

          podman run --rm \
            -v /tmp/test.sh:/tmp/test.sh \
            ${{ env.IMAGE_REF }} \
            /bin/bash /tmp/test.sh

  build-iso:
    name: Build ISO
    needs: [build-image, test-image]
    uses: alexiri/build_image/.github/workflows/build-iso.yml@main
    with:
      image-name: "${{ github.event.repository.name }}"
      image: ${{ needs.build-image.outputs.image-ref }}@${{ needs.build-image.outputs.digest }}
      update_origin_ref: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest"
      config-file: iso.toml
      platforms: "amd64" #"amd64,arm64"

  promote-image:
    name: Promote image
    needs: [build-image, test-image]
    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    uses: alexiri/build_image/.github/workflows/retag-image.yml@main
    with:
      image: ${{ needs.build-image.outputs.image-ref }}@${{ needs.build-image.outputs.digest }}
      tag: latest # ${{ env.LATEST_TAG }}
    secrets:
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: write
